// AssetFamily enum defines high-level asset families for the TMI platform
export enum AssetFamily {
  AVATAR_BODY = "AVATAR_BODY",
  HAIRSTYLE = "HAIRSTYLE",
  WARDROBE = "WARDROBE",
  COSTUME = "COSTUME",
  ACCESSORY = "ACCESSORY",
  PROP = "PROP",
  PERFORMER_VENUE = "PERFORMER_VENUE",
  FAN_LOBBY_ENVIRONMENT = "FAN_LOBBY_ENVIRONMENT",
  LOUNGE_ENVIRONMENT = "LOUNGE_ENVIRONMENT",
  ENVIRONMENT_DECOR = "ENVIRONMENT_DECOR",
}
