"use strict";(()=>{var e={};e.id=10888,e.ids=[10888],e.modules={220399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},430517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},540115:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>y,patchFetch:()=>w,requestAsyncStorage:()=>x,routeModule:()=>g,serverHooks:()=>h,staticGenerationAsyncStorage:()=>f});var o={};r.r(o),r.d(o,{POST:()=>m,dynamic:()=>l});var s=r(863036),i=r(905736),n=r(915262),a=r(960942),p=r(323450);let l="force-dynamic",u=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,d=new Map;function c(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}async function m(e){let t;if(function(e){let t=Date.now(),r=d.get(e);return!r||t-r.windowStart>6e4?(d.set(e,{count:1,windowStart:t}),!1):r.count>=5||(r.count++,!1)}(e.headers.get("x-forwarded-for")?.split(",")[0]?.trim()??e.headers.get("x-real-ip")??"unknown"))return a.NextResponse.json({ok:!1,error:"Too many requests. Try again later."},{status:429});try{t=await e.json()}catch{return a.NextResponse.json({ok:!1,error:"Invalid JSON"},{status:400})}let{name:r,email:o,subject:s,message:i}=t;if(!r||"string"!=typeof r||r.trim().length<1)return a.NextResponse.json({ok:!1,error:"Name is required"},{status:400});if(!o||!u.test(o))return a.NextResponse.json({ok:!1,error:"Valid email is required"},{status:400});if(!s||"string"!=typeof s||s.trim().length<1)return a.NextResponse.json({ok:!1,error:"Subject is required"},{status:400});if(!i||"string"!=typeof i||i.trim().length<10)return a.NextResponse.json({ok:!1,error:"Message must be at least 10 characters"},{status:400});let n=c(r.trim().slice(0,100)),l=c(o.trim().slice(0,254)),m=c(s.trim().slice(0,200)),g=c(i.trim().slice(0,2e3)),x=process.env.TEAM_EMAIL??"support@themusiciansindex.com",f=`
    <div style="font-family:Arial,sans-serif;background:#0A0A0F;color:#E0E0E0;padding:24px;border-radius:8px;">
      <h2 style="color:#00FFFF;margin:0 0 16px;">TMI Support Request</h2>
      <table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;">
        <tr>
          <td style="padding:8px 16px 8px 0;color:#888;font-size:13px;white-space:nowrap;vertical-align:top;">From</td>
          <td style="padding:8px 0;color:#E0E0E0;font-size:15px;">${n} &lt;${l}&gt;</td>
        </tr>
        <tr>
          <td style="padding:8px 16px 8px 0;color:#888;font-size:13px;white-space:nowrap;vertical-align:top;">Subject</td>
          <td style="padding:8px 0;color:#E0E0E0;font-size:15px;font-weight:700;">${m}</td>
        </tr>
        <tr>
          <td style="padding:8px 16px 8px 0;color:#888;font-size:13px;white-space:nowrap;vertical-align:top;">Message</td>
          <td style="padding:8px 0;color:#E0E0E0;font-size:15px;line-height:1.7;white-space:pre-wrap;">${g}</td>
        </tr>
      </table>
    </div>
  `,h=await (0,p.C)({to:x,subject:`[TMI Support] ${m} — from ${n}`,html:f,replyTo:o.trim()});return h.ok?a.NextResponse.json({ok:!0}):(console.error("[support/route] Failed to send support email:",h.error),a.NextResponse.json({ok:!1,error:"Failed to send support email. Please try again."},{status:502}))}let g=new s.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/support/route",pathname:"/api/support",filename:"route",bundlePath:"app/api/support/route"},resolvedPagePath:"C:\\Users\\Admin\\Documents\\BerntoutGlobal XXL\\tmi-platform\\apps\\web\\src\\app\\api\\support\\route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:x,staticGenerationAsyncStorage:f,serverHooks:h}=g,y="/api/support/route";function w(){return(0,n.patchFetch)({serverHooks:h,staticGenerationAsyncStorage:f})}},323450:(e,t,r)=>{r.d(t,{C:()=>n});let o=process.env.EMAIL_FROM_ADDRESS??"noreply@themusiciansindex.com",s=process.env.EMAIL_FROM_NAME??"TMI Platform",i=`${s} <${o}>`;async function n(e){let t=process.env.RESEND_API_KEY;if(!t)return console.log("[TmiEmail] DEV MODE — would send:",e.to,e.subject),{ok:!0,id:`dev-${Date.now()}`};try{let r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({from:i,to:e.to,subject:e.subject,html:e.html,reply_to:e.replyTo})});if(!r.ok){let e=await r.text();return console.error("[TmiEmail] Send failed:",r.status,e),{ok:!1,error:e}}let o=await r.json();return{ok:!0,id:o.id}}catch(e){return console.error("[TmiEmail] Exception:",e),{ok:!1,error:String(e)}}}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),o=t.X(0,[44522,51746],()=>r(540115));module.exports=o})();