import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service'; // Adjust path if Prisma module is elsewhere

@Injectable()
export class ParticipationLedgerService {
  private readonly logger = new Logger(ParticipationLedgerService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Append-only record of a user's participation event.
   * Forms the basis of the Universal Economy Spine points system.
   */
  async recordParticipation(userId: string, actionType: string, points: number, metadata?: Record<string, any>) {
    try {
      const record = await this.prisma.participationLedger.create({
        data: {
          userId,
          actionType,
          points,
          metadata: metadata || {},
          // timestamp is auto-generated by DB @default(now())
        }
      });
      
      this.logger.log(`Participation recorded: User ${userId} earned ${points} pts for ${actionType}`);
      return record;
    } catch (error) {
      this.logger.error(`Failed to record participation for user ${userId}:`, error);
      throw error;
    }
  }

  /**
   * Fetches the participation history for audit and profile display.
   */
  async getHistory(userId: string, limit: number = 50) {
    return this.prisma.participationLedger.findMany({
      where: { userId },
      orderBy: { timestamp: 'desc' },
      take: limit,
    });
  }

  async getActiveSessions(userId: string) {
    // Implementation for active session tracking
    return this.prisma.participationSession.findMany({ where: { userId, active: true } });
  }
}