import React from 'react';
import TMIOverlaySystem from '../foundation-visual/TMIOverlaySystem';
import ArticleFeatureCard from '../foundation-visual/ArticleFeatureCard';

interface ArtistProfileProps {
  artistName: string;
  rank: number;
  level: number;
  xp: number;
  sponsorBrand?: string;
  autoGeneratedArticles: Array<{ id: string; title: string; category: string; imageUrl: string }>;
}

/**
 * ArtistProfileHub: Automatically maps data from the "Profiles" PDF.
 * Handles dynamic ranking, leveling, and auto-generated performer articles.
 */
export default function ArtistProfileHub({ artistName, rank, level, xp, sponsorBrand, autoGeneratedArticles }: ArtistProfileProps) {
  return (
    <div className="relative min-h-screen bg-black text-zinc-100 overflow-hidden font-sans">
      {/* TMI PDF Mapped Overlays */}
      <TMIOverlaySystem shape="cinematic-vignette" opacity={60} />
      <TMIOverlaySystem shape="hologram-grid" opacity={20} />

      <main className="relative z-10 max-w-7xl mx-auto p-8 pt-24 flex flex-col gap-12">
        {/* Header & Ranking Chain */}
        <header className="flex justify-between items-end border-b border-fuchsia-500/30 pb-8">
          <div>
            <h1 className="text-6xl font-black italic uppercase tracking-tighter text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-fuchsia-500">
              {artistName}
            </h1>
            {sponsorBrand && (
              <p className="text-yellow-500 text-sm font-bold tracking-widest mt-2 uppercase">
                Backed by {sponsorBrand}
              </p>
            )}
          </div>
          <div className="text-right">
            <p className="text-3xl font-black text-cyan-400">RANK #{rank}</p>
            <p className="text-zinc-400 text-sm font-bold uppercase tracking-widest mt-1">Level {level} | {xp} XP</p>
          </div>
        </header>

        {/* Auto-Generated Magazine Articles mapped from "The Musicians Index Magazine Images" */}
        <section>
          <h2 className="text-2xl font-black italic text-zinc-300 uppercase tracking-widest mb-6">Latest Press & Coverage</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {autoGeneratedArticles.map((article) => (
              <div key={article.id} className="transform transition-all hover:scale-105 hover:shadow-[0_0_30px_rgba(34,211,238,0.3)]">
                <ArticleFeatureCard title={article.title} category={article.category} imageUrl={article.imageUrl} />
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}